name = "stacky"
version = "1.4.0"
description = "BEAM stack trace in Gleam: a stack trace of stack frames with module name, function name, arity, file name and line number."
licences = ["MPL-2.0"]
repository = { type = "github", user = "inoas", repo = "stacky" }

gleam = ">= 1.0.0 and < 2.0.0"
target = "erlang"

[dependencies]
gleam_stdlib = ">= 0.38.0 and < 2.0.0"
pprint = ">= 1.0.3 and < 2.0.0"
gleam_erlang = ">= 0.25.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.1.2 and < 2.0.0"
